
version: '2.1'

#volumes:
#  emberosf-sync:
#    external: true

services:

#  fakecas:
#    image: quay.io/centerforopenscience/fakecas:latest
#    command: fakecas -host=0.0.0.0:8080 -dbaddress=172.19.0.7:27017

#  wb:
#    volumes_from:
#      - container:wb-sync

#  wb_worker:
#    volumes_from:
#      - container:wb-sync

#  wb_requirements:
#    volumes_from:
#      - container:wb-sync

#  mfr:
#    volumes_from:
#      - container:mfr-sync

#  mfr_requirements:
#    volumes_from:
#      - container:mfr-sync

#  preprints:
#    volumes_from:
#      - container:preprints-sync
##     environment:
##       - ENABLE_PROVIDER_DOMAINS=true
#########    Use this for ember-osf linked development (with docker-sync): #############
#    depends_on:
#      - emberosf
#    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link ember-osf && yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4200"
#    volumes:
#      - preprints_dist_vol:/code/dist
#      - emberosf-sync:/ember-osf
########################################################################################
#
#  registries:
#    volumes_from:
#      - container:registries-sync
#########    Use this for ember-osf linked development (with docker-sync): #############
#    depends_on:
#      - emberosf
#    command: /bin/bash -c "cd /ember-osf && yarn link && cd /code && yarn link ember-osf && yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4300"
#    volumes:
#      - registries_dist_vol:/code/dist
#      - emberosf-sync:/ember-osf
########################################################################################
#
#########    Use this for ember-osf linked development (with docker-sync): #############
#  emberosf:
#    build: ../ember-osf
#    command: /bin/bash -c "yarn --pure-lockfile && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false"
#    volumes:
#      - emberosf-sync:/code/
########################################################################################

  requirements:
    volumes_from:
      - container:osf-sync

  assets:
    volumes_from:
      - container:osf-sync

  admin_assets:
    volumes_from:
      - container:osf-sync

  sharejs:
    volumes_from:
      - container:osf-sync

#  beat:
#    volumes_from:
#      - container:osf-sync

  worker:
    volumes_from:
      - container:osf-sync

  admin:
    volumes_from:
      - container:osf-sync

  web:
    volumes_from:
      - container:osf-sync

  api:
    volumes_from:
      - container:osf-sync
